/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CreateConnectionCallbacks {
  onOpen: (...args: any[]) => any
  onMessage: (...args: any[]) => any
  onError: (...args: any[]) => any
  onClose: (...args: any[]) => any
  url: string
}
export declare function createConnection(options: CreateConnectionCallbacks): CreateWebSocketConnectionResult
export declare class CreateWebSocketConnectionResult {
  send(payload: string): void
}
